# 装饰器

## 方法重试装饰器

```python
import time


# 代理重试方法，默认重试10次
def retry_agent(fun=None, retry_count=10, sleep_time=0.3):
    def decorator(func):
        # 复制副本到代理函数的retry_count变量中
        def agent_method(*args, retry_count=retry_count, **kwargs):
            # 最近的非全局作用域（通常是嵌套函数的外层函数作用域），相当于函数运行时的外层函数作用域
            # 注意：被装饰的目标函数调用时共享此变量的值，也就是重复调用被装饰的函数，并不会每次都初始化此变量
            # nonlocal retry_count
            while True:
                if retry_count > 0:
                    try:
                        result = func(*args, **kwargs)
                        return result
                    except Exception as e:
                        import traceback
                        # 获取详细的异常信息，包括代码行数
                        error_msg = traceback.format_exc()
                        print(error_msg)

                        retry_count -= 1
                        time.sleep(sleep_time)
                else:
                    raise Exception("重复次数超出限制")

        return agent_method

    # 对于@retry_agent用法
    if fun:
        return decorator(fun)
    # 对于@retry_agent()用法或者@retry_agent(sleep_time=1, sleep_time=0.5)用法
    return decorator


@retry_agent(sleep_time=1)
def method(param):
    print("方法参数：", param)


if __name__ == '__main__':
    method(10)

```

## 异常装饰器

```python
from tkinter import messagebox
import time


# 自定义异常类
class CustomException(Exception):
    def __init__(self, message="运行出现异常"):
        self.message = message
        super().__init__(self.message)


# 代理函数，捕捉异常
def catch_custom_exception(func):
    def wrapper(*args, **kwargs):
        try:
            return func(*args, **kwargs)
        except CustomException as e:
            messagebox.showerror(f"发生错误", f"{e}")
        except Exception as e:
            messagebox.showerror(f"发生未知错误", f"{e}")
    return wrapper


# 代理函数，捕捉类方法异常
def catch_custom_exception(func):
    def wrapper(self, *args, **kwargs):
        try:
            return func(self, *args, **kwargs)
        except CustomException as e:
            messagebox.showerror("发生错误", f"{e}")
        except Exception as e:
            messagebox.showerror("发生未知错误", f"{e}")
    return wrapper


# 计算函数运行时间
def calculate_time(func):
    def wrapper(*args, **kwargs):
        start_time = time.time()
        result = func(*args, **kwargs)
        end_time = time.time()
        print(f"函数 {func.__name__} 运行时间为: {end_time - start_time:.4f} 秒")
        return result
    return wrapper

```

## 异步装饰器

```python
from functools import wraps

def sql_exception(func):
    @wraps(func)
    async def wrapper(*args, **kwargs):
        try:
            print("-----------------------")
            return await func(*args, **kwargs)
        except SQLException as e:
            pass
    return wrapper

```

